import type { LucideIcon } from 'lucide-react';
import {
  Heart,
  Ghost,
  Utensils,
  Shuffle,
  RotateCcw,
  Eye,
  TrendingDown,
  Thermometer,
  FileText,
  DollarSign,
  AlertCircle,
  TrendingUp,
  Building2,
  Handshake,
  ThumbsDown,
  Coffee,
  Mic,
  Scale,
  AlertTriangle,
  Flame,
  Brain,
  CalendarX,
  Award,
  UserCheck,
  Send,
  BarChart2,
  Users,
  GraduationCap,
  Package,
  BellOff,
  Building,
  HelpCircle,
  Megaphone,
  Clock,
  HeartCrack,
  FileCheck,
  Home,
  ShieldCheck,
  Percent,
} from 'lucide-react';
import type { CommunicationMode } from '@/types/database';

export interface Template {
  id: string;
  title: string;
  description: string;
  icon: LucideIcon;
  mode: CommunicationMode;
  message: string;
  context?: string;
  objective?: string;
  isPro: boolean;
}

export const TEMPLATES: Template[] = [
  // ─── DATING ────────────────────────────────────────────────────────────────
  {
    id: 'dating-passive',
    title: 'Le message tiède',
    description: 'Il/elle confirme à moitié, sans enthousiasme',
    icon: Thermometer,
    mode: 'dating',
    message: 'Bon ok, on se voit samedi si tu veux',
    context: 'On avait prévu de se retrouver, mais le message manque clairement de warmth',
    objective: 'Reprendre le contrôle sans paraître trop demandeur',
    isPro: false,
  },
  {
    id: 'dating-silence',
    title: 'Le silence de 3 jours',
    description: 'Aucune réponse depuis plusieurs jours après une conversation qui se passait bien',
    icon: Ghost,
    mode: 'dating',
    message: 'Coucou ! Désolé j\'avais pas vu ton message, j\'étais pas mal pris 😅 comment tu vas ?',
    context: 'Après 3 jours sans nouvelles, il/elle revient avec une excuse banale',
    objective: 'Ne pas lui faciliter la vie, garder ma valeur sans être froid',
    isPro: true,
  },
  {
    id: 'dating-after-date',
    title: 'Après le 1er rendez-vous',
    description: 'Lendemain de RDV — message flou, impossible de savoir si ça l\'a intéressé',
    icon: Utensils,
    mode: 'dating',
    message: 'J\'ai passé une bonne soirée 😊',
    context: 'Premier rendez-vous hier soir, ça s\'est bien passé de mon côté, mais son message est très plat',
    objective: 'Créer une suite sans paraître trop pressé ni perdre l\'intérêt',
    isPro: true,
  },
  {
    id: 'dating-hot-cold',
    title: 'Le soufflant-glaçant',
    description: 'Un jour enthousiaste, le lendemain fantôme — le cycle classique',
    icon: Shuffle,
    mode: 'dating',
    message: 'Haha ouais c\'est pas faux... bon je dois y aller là, à plus !',
    context: 'Après 30 min d\'échange animé, il/elle coupe court sans raison',
    objective: 'Stopper le pattern en reprenant l\'initiative',
    isPro: true,
  },
  {
    id: 'dating-ex-contact',
    title: 'L\'ex qui revient',
    description: 'Reprise de contact après 2-3 mois de silence total',
    icon: RotateCcw,
    mode: 'dating',
    message: 'Salut, ça fait longtemps... comment tu vas ?',
    context: 'On a rompu il y a 3 mois, c\'était compliqué. Il/elle revient sans explication',
    objective: 'Rester en position de force, ne pas tomber dans le piège de la nostalgie',
    isPro: true,
  },
  {
    id: 'dating-jealousy',
    title: 'La pique passive-agressive',
    description: 'Un message sous-entendu pour tester ta réaction ou te rendre jaloux',
    icon: Eye,
    mode: 'dating',
    message: 'Bon bah j\'étais occupée ce week-end de toute façon, j\'avais plein de trucs prévus avec des amis 😄',
    context: 'Je n\'avais pas donné de nouvelles pendant le week-end, et là elle le met en avant',
    objective: 'Ne pas réagir comme elle l\'attend, garder ma sérénité',
    isPro: true,
  },
  {
    id: 'dating-slowfade',
    title: 'Le slow fade',
    description: 'Les réponses s\'espacent, les messages raccourcissent',
    icon: TrendingDown,
    mode: 'dating',
    message: 'Ouais lol',
    context: 'Après une semaine de messages de plus en plus courts, c\'est le fond',
    objective: 'Soit clarifier la situation, soit sortir proprement',
    isPro: true,
  },
  {
    id: 'dating-opener-match',
    title: 'Premier message après un match',
    description: 'Il/elle envoie un premier message banal sur une appli',
    icon: Heart,
    mode: 'dating',
    message: 'Salut, comment tu vas ? Tu fais quoi comme boulot ?',
    context: 'Match récent sur une appli de rencontre, premier message très générique',
    objective: 'Sortir du lot sans être bizarre, piquer la curiosité',
    isPro: true,
  },

  // ─── BUSINESS ──────────────────────────────────────────────────────────────
  {
    id: 'business-devis-silence',
    title: 'Le devis fantôme',
    description: 'Ton devis est resté sans réponse depuis 2 semaines',
    icon: FileText,
    mode: 'follow_up',
    message: 'Bonjour, suite à notre échange, j\'ai bien transmis votre proposition à notre direction. Nous revenons vers vous très prochainement.',
    context: 'J\'ai envoyé un devis il y a 2 semaines, suivi d\'un relance il y a 1 semaine. Cette réponse date d\'hier.',
    objective: 'Créer une urgence douce sans paraître désespéré',
    isPro: false,
  },
  {
    id: 'business-refus-budget',
    title: 'Budget insuffisant',
    description: 'Le client aime mais dit que le prix est trop élevé',
    icon: DollarSign,
    mode: 'negotiation',
    message: 'Votre proposition est intéressante mais elle dépasse notre budget. Seriez-vous en mesure de revoir votre tarif ?',
    context: 'Client intéressé par mes services, mais il négocie sur le prix',
    objective: 'Défendre ma valeur sans perdre le deal',
    isPro: true,
  },
  {
    id: 'business-client-mecontent',
    title: 'Le client mécontent',
    description: 'Retour négatif sur une prestation ou livraison',
    icon: AlertCircle,
    mode: 'conflict',
    message: 'Honnêtement je suis déçu du résultat. Ce n\'est pas ce qu\'on avait convenu et les délais n\'ont pas été respectés.',
    context: 'Projet livré hier, le client réagit négativement, même si les retards étaient en partie de son fait',
    objective: 'Désamorcer sans m\'écraser, trouver une solution',
    isPro: true,
  },
  {
    id: 'business-augmentation-refus',
    title: 'Refus d\'augmentation',
    description: 'RH refuse ta demande de revalorisation salariale',
    icon: TrendingUp,
    mode: 'negotiation',
    message: 'Nous reconnaissons votre contribution mais ne sommes pas en mesure d\'accéder à cette demande en ce moment. Nous en reparlerons lors de la prochaine évaluation.',
    context: 'J\'ai demandé une augmentation de 15% il y a 3 semaines, réponse reçue aujourd\'hui',
    objective: 'Ne pas accepter sans contrepartie, maintenir la pression sans froisser',
    isPro: true,
  },
  {
    id: 'business-hr-silence',
    title: 'Le silence RH',
    description: 'Entretien passé il y a 2 semaines, aucune réponse',
    icon: Building2,
    mode: 'follow_up',
    message: 'Votre candidature a bien été reçue. Nous l\'examinerons avec attention et nous vous contacterons.',
    context: 'Réponse automatique reçue après mon entretien il y a 2 semaines. Toujours rien depuis.',
    objective: 'Relancer sans paraître désespéré, maintenir mon intérêt apparent',
    isPro: true,
  },
  {
    id: 'business-partenaire-reneg',
    title: 'Le partenaire qui renégocie',
    description: 'Un partenaire commercial veut changer les termes du contrat',
    icon: Handshake,
    mode: 'negotiation',
    message: 'Vu l\'évolution du marché, nous aimerions revoir les conditions de notre partenariat. Seriez-vous disponible pour en discuter ?',
    context: 'Partenariat en cours depuis 6 mois, il veut renégocier à son avantage',
    objective: 'Accepter la discussion sans signaler que je suis prêt à céder',
    isPro: true,
  },
  {
    id: 'business-feedback-negatif',
    title: 'Le feedback piquant',
    description: 'Critique directe sur ton travail lors d\'une revue',
    icon: ThumbsDown,
    mode: 'conflict',
    message: 'Je dois être honnête : cette version ne correspond pas à mes attentes. Je m\'attendais à quelque chose de beaucoup plus élaboré.',
    context: 'Présentation d\'une première version d\'un livrable à un client ou manager exigeant',
    objective: 'Rester professionnel sans me dévaloriser, clarifier les attentes',
    isPro: true,
  },
  {
    id: 'business-reseau',
    title: 'La demande réseau froide',
    description: 'Quelqu\'un veut "prendre un café" pour que tu l\'aides',
    icon: Coffee,
    mode: 'cold_polite',
    message: 'Bonjour, je suis votre parcours depuis longtemps et j\'aimerais beaucoup avoir votre avis sur mon projet. Seriez-vous disponible pour un café ?',
    context: 'Demande d\'un inconnu sur LinkedIn, clairement orienté vers obtenir quelque chose',
    objective: 'Être ouvert sans me laisser exploiter mon temps gratuitement',
    isPro: true,
  },

  // ─── CONFLICT ──────────────────────────────────────────────────────────────
  {
    id: 'conflict-reunion-coupe',
    title: 'Coupé en réunion',
    description: 'Un collègue a pris ta parole ou écarté ton idée en réunion',
    icon: Mic,
    mode: 'conflict',
    message: 'Oui comme je le disais, l\'idée c\'est de faire X. [Il a repris exactement ton idée 10 minutes plus tard]',
    context: 'En réunion tout à l\'heure, un collègue a coupé ma présentation puis a réexposé mon idée comme si c\'était la sienne',
    objective: 'Recadrer le comportement sans faire une scène, reprendre ma place',
    isPro: false,
  },
  {
    id: 'conflict-accusation',
    title: 'L\'accusation injuste',
    description: 'On te reproche quelque chose que tu n\'as pas fait ou mal interprété',
    icon: Scale,
    mode: 'conflict',
    message: 'Je ne comprends pas pourquoi tu as fait ça, c\'est vraiment décevant. Je m\'attendais à mieux de ta part.',
    context: 'Message d\'un collègue ou d\'un ami qui m\'accuse d\'un comportement que je n\'ai pas eu ou qui est mal compris',
    objective: 'Me défendre avec calme et clarté sans m\'emporter',
    isPro: true,
  },
  {
    id: 'conflict-ami-blessant',
    title: 'L\'ami qui a dépassé les bornes',
    description: 'Un ami a dit ou fait quelque chose de blessant et ne s\'en rend pas compte',
    icon: AlertTriangle,
    mode: 'conflict',
    message: 'Allez arrête de faire ta victime, tu dramatises comme d\'habitude 😄',
    context: 'En réponse à quelque chose qui m\'a vraiment blessé, l\'ami minimise et tourne ça en dérision',
    objective: 'Exprimer que c\'est sérieux sans que ça devienne une guerre',
    isPro: true,
  },
  {
    id: 'conflict-agressif',
    title: 'Le message agressif',
    description: 'Tu reçois un message véritablement hostile ou menaçant',
    icon: Flame,
    mode: 'conflict',
    message: 'J\'en ai marre de tes comportements. Si tu continues comme ça je vais devoir en parler à qui de droit.',
    context: 'Message d\'un collègue, client ou connaissance visiblement hors de lui',
    objective: 'Rester ferme et calme, ne pas entrer dans son jeu mais ne pas capituler',
    isPro: true,
  },
  {
    id: 'conflict-gaslighting',
    title: 'La réalité réécrite',
    description: 'L\'autre remet en question ta version des faits',
    icon: Brain,
    mode: 'conflict',
    message: 'Non mais t\'as mal compris, c\'est pas du tout ce que j\'ai dit. T\'as tendance à te braquer sur des riens.',
    context: 'L\'interlocuteur nie avoir dit quelque chose que j\'ai clairement entendu',
    objective: 'Maintenir ma version sans m\'énerver, recadrer le comportement',
    isPro: true,
  },

  // ─── FRIENDLY ──────────────────────────────────────────────────────────────
  {
    id: 'friendly-annulation',
    title: 'L\'annulation de dernière minute',
    description: 'Un ami annule une soirée à 2h du lancement',
    icon: CalendarX,
    mode: 'friendly',
    message: 'Mec je suis vraiment désolé, je suis à plat ce soir, j\'arrive pas à venir. On reporte ?',
    context: 'C\'est la 3ème fois en 2 mois qu\'il annule au dernier moment',
    objective: 'Dire que c\'est pas cool sans briser l\'amitié',
    isPro: false,
  },
  {
    id: 'friendly-debt',
    title: 'L\'argent oublié',
    description: 'Un ami doit te rembourser depuis un moment et ne dit rien',
    icon: DollarSign,
    mode: 'friendly',
    message: 'Ça fait longtemps qu\'on s\'est pas vu ! On fait quelque chose bientôt ?',
    context: 'Un ami qui me doit 80€ depuis 2 mois me contacte pour qu\'on se voie, sans mentionner la dette',
    objective: 'Mentionner le remboursement sans ruiner l\'ambiance',
    isPro: true,
  },
  {
    id: 'friendly-jalousie',
    title: 'La jalousie d\'ami',
    description: 'Un ami réagit mal à tes succès ou minimise tes accomplissements',
    icon: Award,
    mode: 'friendly',
    message: 'Ouais cool. C\'est sûr que quand on a de la chance ça aide.',
    context: 'Je viens d\'annoncer une bonne nouvelle, la réaction est froide et un peu piquante',
    objective: 'Maintenir ma joie sans entrer dans une confrontation',
    isPro: true,
  },
  {
    id: 'friendly-distance',
    title: 'La reprise de contact',
    description: 'Un ami perdu de vue revient après 6 mois sans nouvelles',
    icon: UserCheck,
    mode: 'friendly',
    message: 'Heeey ! Ça fait longtemps dis donc 😅 tu deviens un fantôme toi ! Comment tu vas ?',
    context: 'Ami qui réapparaît après un silence de plusieurs mois, sans explication',
    objective: 'Être chaleureux mais marquer que sa disparition n\'était pas invisible',
    isPro: true,
  },

  // ─── FOLLOW-UP ─────────────────────────────────────────────────────────────
  {
    id: 'followup-candidature',
    title: 'Relance candidature',
    description: 'Tu as candidaté il y a 3 semaines, rien depuis',
    icon: Send,
    mode: 'follow_up',
    message: '[Silence — aucune réponse à ton mail de candidature]',
    context: 'Candidature envoyée il y a 3 semaines pour un poste qui m\'intéresse vraiment. Pas de réponse.',
    objective: 'Relancer sans paraître désespéré, montrer que je suis toujours intéressé',
    isPro: false,
  },
  {
    id: 'followup-investisseur',
    title: 'L\'investisseur silencieux',
    description: 'Suite à un pitch, l\'investisseur n\'a plus donné signe de vie',
    icon: BarChart2,
    mode: 'follow_up',
    message: '[Silence — plus de réponse après 2 relances]',
    context: 'Pitch fait il y a 3 semaines, 2 relances restées sans réponse. Avancée ou abandon ?',
    objective: 'Créer une dernière opportunité de réponse sans paraître dans le besoin',
    isPro: true,
  },
  {
    id: 'followup-client-fantome',
    title: 'Le client fantôme',
    description: 'Intéressé lors du premier appel, introuvable depuis',
    icon: Ghost,
    mode: 'follow_up',
    message: 'Ah oui bien sûr je regarde ça et je reviens vers vous rapidement !',
    context: 'Message reçu il y a 10 jours, aucune réponse à mes 2 relances depuis',
    objective: 'Provoquer une réponse finale — oui ou non, mais sortir de l\'incertitude',
    isPro: true,
  },
  {
    id: 'followup-collaboration',
    title: 'Collaboration proposée',
    description: 'Tu as proposé une collaboration, réponse enthousiaste mais plus rien',
    icon: Users,
    mode: 'follow_up',
    message: 'Super idée ! Je suis vraiment partant, on en reparle très vite !',
    context: 'Message reçu il y a 3 semaines, depuis le silence complet',
    objective: 'Relancer sans brûler le pont, créer une date concrète',
    isPro: true,
  },
  {
    id: 'followup-mentor',
    title: 'Relance d\'un mentor',
    description: 'Tu attends un retour d\'un contact important ou d\'un mentor',
    icon: GraduationCap,
    mode: 'follow_up',
    message: 'Je t\'envoie mes retours la semaine prochaine, promis !',
    context: 'Il y a 3 semaines, promesse de feedback. Toujours rien.',
    objective: 'Obtenir le retour sans paraître insistant ni irrespectueux',
    isPro: true,
  },
  {
    id: 'followup-fournisseur',
    title: 'Fournisseur lent',
    description: 'Commande passée, livraison en retard, personne ne répond',
    icon: Package,
    mode: 'follow_up',
    message: 'Votre commande est en cours de traitement. Un conseiller prendra contact avec vous.',
    context: 'Commande payée il y a 15 jours, délai annoncé 7 jours. Personne ne répond.',
    objective: 'Obtenir une réponse ferme avec une date précise sans être agressif',
    isPro: true,
  },

  // ─── COLD POLITE ───────────────────────────────────────────────────────────
  {
    id: 'cold-envahissant',
    title: 'Le contact envahissant',
    description: 'Quelqu\'un t\'envoie des messages à répétition sans que tu le valides',
    icon: BellOff,
    mode: 'cold_polite',
    message: 'Coucou ! Tu as eu le temps de réfléchir à ma proposition ? Je voulais te recontacter parce que c\'est vraiment une opportunité unique',
    context: 'Troisième message en 10 jours d\'un contact dont je veux garder la distance',
    objective: 'Fermer la porte poliment mais définitivement',
    isPro: false,
  },
  {
    id: 'cold-ex-professionnel',
    title: 'L\'ex-collègue insistant',
    description: 'Un ancien collègue cherche à te réimpliquer dans quelque chose',
    icon: Building,
    mode: 'cold_polite',
    message: 'Salut ! Je pense souvent à notre collaboration. J\'ai un projet en ce moment qui correspond exactement à ce qu\'on faisait. Tu serais dispo pour en parler ?',
    context: 'Ancien collègue avec qui la séparation s\'était bien passée mais je ne veux pas retravailler avec lui',
    objective: 'Rester cordial tout en fermant la porte',
    isPro: true,
  },
  {
    id: 'cold-connaissance-faveur',
    title: 'La grosse faveur inattendue',
    description: 'Une connaissance lointaine demande une grosse faveur',
    icon: HelpCircle,
    mode: 'cold_polite',
    message: 'Salut ! Je sais qu\'on se connaît pas très bien mais j\'ai pensé à toi pour ça. Tu pourrais m\'aider à [tâche importante] ? Ça serait vraiment précieux',
    context: 'Quelqu\'un que je croise rarement me demande un service significatif',
    objective: 'Refuser sans faire de vague et sans paraître antipathique',
    isPro: true,
  },
  {
    id: 'cold-vente',
    title: 'Le pitch commercial non sollicité',
    description: 'Un commercial ou prestataire t\'est envoyé sans que tu l\'aies demandé',
    icon: Megaphone,
    mode: 'cold_polite',
    message: 'Bonjour, je me permets de vous contacter car j\'ai une solution qui pourrait vraiment transformer votre business. Avez-vous 15 minutes cette semaine ?',
    context: 'Email ou message non sollicité d\'un commercial que je ne connais pas',
    objective: 'Répondre pour couper court sans créer d\'hostilité inutile',
    isPro: true,
  },

  // ─── APOLOGY ───────────────────────────────────────────────────────────────
  {
    id: 'apology-ami-retard',
    title: 'L\'excuse de l\'ami',
    description: 'Un ami s\'excuse pour un retard ou un oubli, que répondre ?',
    icon: Clock,
    mode: 'apology',
    message: 'Pardon pardon pardon ! Je suis vraiment navré pour hier, c\'était nul de ma part 😔',
    context: 'Un ami m\'a posé un lapin hier, aujourd\'hui il s\'excuse',
    objective: 'Accepter sans effacer entièrement la faute, maintenir une limite douce',
    isPro: false,
  },
  {
    id: 'apology-partenaire',
    title: 'L\'excuse du partenaire',
    description: 'Un partenaire romantique s\'excuse après une dispute ou un comportement blessant',
    icon: HeartCrack,
    mode: 'apology',
    message: 'Je suis vraiment désolé pour ce que j\'ai dit, tu ne méritais pas ça. J\'ai merdé.',
    context: 'Après une dispute sérieuse d\'hier soir, il/elle s\'excuse',
    objective: 'Accueillir l\'excuse sans régler immédiatement tout, garder de l\'espace',
    isPro: true,
  },
  {
    id: 'apology-pro',
    title: 'Excuse professionnelle reçue',
    description: 'Un collègue ou prestataire s\'excuse pour une erreur qui t\'a impacté',
    icon: FileCheck,
    mode: 'apology',
    message: 'Je tiens à m\'excuser pour le bug en production vendredi. C\'était de mon ressort et j\'aurais dû être plus rigoureux.',
    context: 'Erreur d\'un collègue qui a causé des problèmes sur mon projet',
    objective: 'Accepter l\'excuse professionnellement en ouvrant une discussion constructive',
    isPro: true,
  },

  // ─── NEGOTIATION ───────────────────────────────────────────────────────────
  {
    id: 'negotiation-offre-basse',
    title: 'L\'offre trop basse',
    description: 'Tu reçois une offre de salaire ou de mission en-dessous de tes attentes',
    icon: TrendingDown,
    mode: 'negotiation',
    message: 'Nous aimerions vous proposer un salaire de X€. Qu\'en pensez-vous ?',
    context: 'Offre reçue après un processus de recrutement, le montant est 20% sous mes attentes',
    objective: 'Contre-proposer avec confiance sans fermer la porte',
    isPro: false,
  },
  {
    id: 'negotiation-loyer',
    title: 'Le propriétaire inflexible',
    description: 'Tu négocies un loyer ou des conditions de bail',
    icon: Home,
    mode: 'negotiation',
    message: 'Non non, le prix est fixé, je ne descends pas. C\'est comme ça pour tous les locataires.',
    context: 'Je veux louer un appartement mais le loyer est trop élevé pour moi',
    objective: 'Trouver un levier pour obtenir une concession même mineure',
    isPro: true,
  },
  {
    id: 'negotiation-prestataire-hausse',
    title: 'La hausse de tarif surprise',
    description: 'Un prestataire annonce une augmentation unilatérale',
    icon: TrendingUp,
    mode: 'negotiation',
    message: 'Suite à l\'évolution de nos coûts, nous devons revoir nos tarifs à la hausse de 30% à partir du mois prochain.',
    context: 'Annonce surprise d\'un prestataire dont j\'ai besoin mais dont les tarifs deviennent problématiques',
    objective: 'Négocier pour limiter ou lisser l\'augmentation sans rompre le contrat',
    isPro: true,
  },
  {
    id: 'negotiation-assurance',
    title: 'La compagnie d\'assurance',
    description: 'Refus ou proposition insuffisante d\'indemnisation',
    icon: ShieldCheck,
    mode: 'negotiation',
    message: 'Après examen de votre dossier, nous vous proposons une indemnisation de X€, ce qui correspond à notre évaluation du sinistre.',
    context: 'Proposition d\'indemnisation reçue, qui est clairement en-dessous de la valeur réelle',
    objective: 'Contester de façon argumentée et obtenir une révision à la hausse',
    isPro: true,
  },
  {
    id: 'negotiation-client-prix',
    title: 'Le client qui tire les prix',
    description: 'Un client potentiel demande une remise importante sur ta prestation',
    icon: Percent,
    mode: 'negotiation',
    message: 'C\'est un peu cher pour nous. Est-ce que vous pourriez faire un effort significatif ? Genre -30% ?',
    context: 'Prospect intéressé par ma prestation mais qui cherche à négocier agressivement',
    objective: 'Tenir mes prix en valorisant la qualité, proposer une alternative si besoin',
    isPro: true,
  },
];

export const FREE_TEMPLATE_IDS = TEMPLATES.filter((t) => !t.isPro).map((t) => t.id);

export function getTemplatesByMode(mode?: CommunicationMode): Template[] {
  if (!mode) return TEMPLATES;
  return TEMPLATES.filter((t) => t.mode === mode);
}

export function getTemplateById(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}
